### ISSUE TITLE
different versions in Unreal editor

### ISSUE THREAD

**Issue by lahtis** [SiebenCorgie/Beta-Launcher#10]
I have a manually build Unreal editor in source UE 4.14 and UE 4.15 versions. Now im trying add Substance plugin for Unreal 4.15 copy. Can I give the address in program where the different versions can be found. And use beta-launcher.

**Comment by SiebenCorgie** [comment]
Yeah, the launcher needs to know where your different versions are(You can change this in the preferences). However, they should be placed like this:
EnginesFolder: Folder name "4.15"-> Subfolder name: "UnrealEngine"
                         Folder name "4.14" -> Subfolder name: "UnrealEngine"
That's they way the launcher would install different UE4 versions.
Otherwise the start procedure wont find the executable of the editor. 

For the Plugin, you only need Substance Designer's PluginFolder, have a look here, I asked the same question:[https://answers.unrealengine.com/questions/537516/substance-plugin-on-linux.html?sort=oldest]( https://answers.unrealengine.com/questions/537516/substance-plugin-on-linux.html?sort=oldest )
